=== jan-vcapgemini/lexeme/src/main/resources/xsd/MergeSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://may-bee.github.io/lexeme/mergeschema"
  xmlns:ms="http://may-bee.github.io/lexeme/mergeschema" elementFormDefault="qualified">

  <complexType name="Content">
    <attribute name="attachable" type="boolean" use="optional" default="false"></attribute>
    <attribute name="separationString" type="string" use="optional" default=""></attribute>
  </complexType>

  <complexType name="DefaultCriterionType">
    <attribute name="xpath" type="ms:xpath" default="./*" use="optional"></attribute>
    <attribute name="ordered" type="boolean" default="false" use="optional"/>
  </complexType>

  <complexType name="Handling">
    <sequence>
      <element name="Criterion" type="ms:Criterion" maxOccurs="unbounded" minOccurs="0">
      </element>
      <element name="Handling" type="ms:Handling" maxOccurs="unbounded" minOccurs="0">
      </element>
      <element name="Attribute" type="ms:Attribute" maxOccurs="unbounded" minOccurs="0">
      </element>
      <element name="Content" type="ms:Content" maxOccurs="1" minOccurs="0">
      </element>
    </sequence>
    <attribute name="for" type="string" use="required"></attribute>
    <attribute name="unique" type="boolean" use="optional" default="false"></attribute>
    <attribute name="where" type="ms:xpath" use="optional" default="true()"></attribute>
    <attribute name="scope-ref" type="string" use="optional" default=""/>
    <attribute name="namespace-ref" type="string" use="optional" default=""/>
    <attribute name="label" type="string" use="optional" default=""/>
    <attribute name="attachable-text" type="boolean" use="optional" default="false"/>

  </complexType>

  <complexType name="MergeSchema">
    <complexContent>
      <extension base="ms:Handling">
        <sequence>
          <element name="Definition" type="ms:Definition" maxOccurs="1" minOccurs="1"></element>
          <element name="DefaultCriterion" type="ms:DefaultCriterionType" minOccurs="0"/>
        </sequence>
        <attribute name="root" type="boolean" use="optional" default="true"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Definition">
    <sequence>
      <element name="AdditionalNamespace" type="ms:AdditionalNamespace" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="location" type="string" use="optional" default=""></attribute>
    <attribute name="type" type="ms:schemaType" use="optional" default="xsd"></attribute>
    <attribute name="namespace" type="string" use="required"></attribute>
  </complexType>

  <simpleType name="schemaType">
    <restriction base="string">
      <enumeration value="dtd"></enumeration>
      <enumeration value="xsd"></enumeration>
    </restriction>
  </simpleType>

  <element name="MergeSchema" type="ms:MergeSchema"></element>

  <complexType name="Criterion">
    <attribute name="xpath" type="ms:xpath" use="optional" default="./*"></attribute>
    <attribute name="ordered" type="boolean" use="optional" default="false"></attribute>
  </complexType>

  <complexType name="Attribute">
    <attribute name="for" type="string" use="required"></attribute>
    <attribute name="attachable" type="boolean" use="optional" default="false"></attribute>
    <attribute name="separationString" type="string" use="optional" default=""></attribute>
  </complexType>

  <complexType name="AdditionalNamespace">
    <attribute name="location" type="string" use="optional" default=""></attribute>
    <attribute name="namespace" type="string" use="required"></attribute>
  </complexType>




  <simpleType name="xpath">
    <restriction base="string"></restriction>
  </simpleType>



</schema>

=== jan-vcapgemini/lexeme/src/main/resources/mergeSchemas/springTransaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<ms:MergeSchema for="" root="false" xmlns:ms="http://may-bee.github.io/lexeme/mergeschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://may-bee.github.io/lexeme/mergeschema ../xsd/MergeSchema.xsd ">
  <ms:Definition namespace="http://www.springframework.org/schema/tx"/>

  <ms:DefaultCriterion xpath="./@id"/>

  <ms:Handling for="advice">
    <ms:Handling for="attributes" type="unique">
    <ms:Criterion xpath="true()"/>
      <ms:Handling for="method">
        <ms:Criterion xpath="./@name"/>
        <ms:Attribute for="rollback-for" attachable="true" separationString=","/>
        <ms:Attribute for="no-rollback-fot" attachable="true" separationString=","/>
      </ms:Handling>
    </ms:Handling>
  </ms:Handling>

  <ms:Handling for="annotation-driven">
    <ms:Criterion xpath="true()"/>
  </ms:Handling>


</ms:MergeSchema>

=== jan-vcapgemini/lexeme/src/main/resources/mergeSchemas/springWebflow.xml
<?xml version="1.0" encoding="UTF-8"?>
<ms:MergeSchema for="flow" xmlns:ms="http://may-bee.github.io/lexeme/mergeschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://may-bee.github.io/lexeme/mergeschema ../xsd/MergeSchema.xsd ">
  <ms:Definition namespace="http://www.springframework.org/schema/webflow"/>
  <ms:DefaultCriterion xpath="./@name"/>

  <ms:Handling for="attribute">
    <ms:Handling for="value" unique="true">
      <ms:Criterion xpath="./"/>
    </ms:Handling>
  </ms:Handling>

  <ms:Handling for="secured" unique="true">
    <ms:Criterion xpath="true()"/>
  </ms:Handling>

  <ms:Handling for="persistence-context" unique="true">
    <ms:Criterion xpath="true()"/>
  </ms:Handling>

  <ms:Handling for="transition">
    <!-- Covers viewTransitions as well since the added attributes are handled via default -->
    <ms:Criterion xpath="./@on"/>
  </ms:Handling>

  <ms:Handling for="global-transitions" unique="true">
    <ms:Criterion xpath="true()"/>
  </ms:Handling>

  <ms:Handling for="exception-handler">
    <ms:Criterion xpath="./@bean"/>
  </ms:Handling>

  <ms:Handling for="bean-import">
    <ms:Criterion xpath="./@resource"/>
  </ms:Handling>

  <!-- Shared state elements -->

  <ms:Handling for="on-start" unique="true">
    <ms:Criterion xpath="true()"/>
  </ms:Handling>

  <ms:Handling for="on-entry" unique="true">
    <ms:Criterion xpath="true()"/>
  </ms:Handling>

  <ms:Handling for="on-exit" unique="true">
    <ms:Content xpath="true()"/>
  </ms:Handling>

  <ms:Handling for="binder">
    <!-- the binder itself works as a container for binding elements. I don't see any properties for a distinction -->
    <ms:Criterion xpath="true()"/>
  </ms:Handling>

  <ms:Handling for="binding">
    <ms:Criterion xpath="./@property"/>
  </ms:Handling>

  <ms:Handling for="on-render" unique="true">
    <ms:Criterion xpath="true()"/>
  </ms:Handling>

  <ms:Handling for="if">
    <ms:Criterion xpath="./@test"/>
  </ms:Handling>

  <!-- States -->

  <ms:Handling for="action-state">
    <ms:Criterion xpath="./@id"/> <!-- TODO -->
  </ms:Handling>

  <ms:Handling for="view-state">
    <ms:Criterion xpath="./@id"/>
  </ms:Handling>

  <ms:Handling for="decision-state">
    <ms:Criterion xpath="./@id"/>
  </ms:Handling>

  <ms:Handling for="subflow-state">
    <ms:Criterion xpath="./@id"/>
  </ms:Handling>

  <ms:Handling for="end-state">
    <ms:Criterion xpath="./@id"/>
  </ms:Handling>

  <!-- Group actionTypes -->

  <ms:Handling for="evaluate">
    <ms:Criterion xpath="./@expression"/>
  </ms:Handling>

  <ms:Handling for="render">
    <ms:Criterion xpath="./@fragments"/>
  </ms:Handling>

</ms:MergeSchema>

=== jan-vcapgemini/lexeme/src/main/resources/mergeSchemas/persistenceOrm.xml
<?xml version="1.0" encoding="UTF-8"?>
<ms:MergeSchema for="entity-mappings" xmlns:ms="http://may-bee.github.io/lexeme/mergeschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://may-bee.github.io/lexeme/mergeschema ../xsd/MergeSchema.xsd ">
  <ms:Definition namespace="http://java.sun.com/xml/ns/persistence/orm"/>

  <ms:DefaultCriterion xpath="./@name"/>

  <ms:Handling for="describtion" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="package" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="schema" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="catalog" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="access" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="persistence-unit-metadata" unique="true">
    <ms:Criterion xpath="true()"/>
    <ms:Handling for="xml-mapping-metadata-complete" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="persistence-unit-defaults" unique="true">
      <ms:Criterion xpath="true()"/>
      <ms:Handling for="cascade-persist" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    </ms:Handling>
  </ms:Handling>
  <ms:Handling for="table-generator">
    <ms:Handling for="unique-constraint"><ms:Criterion xpath="./@column-name"/></ms:Handling>
  </ms:Handling>
  <ms:Handling for="named-query">
    <ms:Handling for="query" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  </ms:Handling>
  <ms:Handling for="named-native-query">
    <ms:Handling for="query" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  </ms:Handling>
  <ms:Handling for="sql-result-set-mapping">
    <ms:Handling for="entity-result"><ms:Criterion xpath="./@entity-class"/></ms:Handling>
  </ms:Handling>
  <ms:Handling for="mapped-superclass">
    <ms:Criterion xpath="./@class"/>
    <ms:Handling for="id-class" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="exclude-default-listeners" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="exclude-superclass-listeners" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  </ms:Handling>
  <ms:Handling for="entity">
    <ms:Handling for="unique-constraint"><ms:Criterion xpath="./@column-name"/></ms:Handling>
    <ms:Handling for="table" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="id-class" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="inheritance" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="discriminator-value" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="discriminator-column" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="sequence-generator" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="table-generator" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="exclude-default-listeners" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="exclude-superclass-listeners" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="column" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  </ms:Handling>
  <ms:Handling for="embeddable">
    <ms:Criterion xpath="./@class"/>
    <ms:Handling for="embeddable-attributes" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  </ms:Handling>

  <!-- shared Handlings -->
  <ms:Handling for="entity-listeners" unique="true">
    <ms:Criterion xpath="true()"/>
    <ms:Handling for="entity-listener"><ms:Criterion xpath="./@class"/></ms:Handling>
  </ms:Handling>
  <ms:Handling for="attributes" unique="true">
      <ms:Criterion xpath="true()"/>
      <ms:Handling for="id">
        <ms:Handling for="column" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
        <ms:Handling for="sequence-generator" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
        <ms:Handling for="temporal" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
        <ms:Handling for="table-generator" unique="true">
           <ms:Criterion xpath="true()"/>
           <ms:Handling for="unique-constraint"><ms:Criterion xpath="./@column-name"/></ms:Handling>
        </ms:Handling>
      </ms:Handling>
      <ms:Handling for="embedded-id" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
      <ms:Handling for="version">
        <ms:Handling for="column" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
        <ms:Handling for="temporal" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
      </ms:Handling>
      <ms:Handling for="join-table" unique="true">
          <ms:Criterion xpath="true()"/>
          <ms:Handling for="unique-constraint"><ms:Criterion xpath="./@column-name"/></ms:Handling>
      </ms:Handling>
      <ms:Handling for="cascade" unique="true">
          <ms:Criterion xpath="true()"/>
          <ms:Handling for="cascade-all"><ms:Criterion xpath="true()"/></ms:Handling>
          <ms:Handling for="cascade-persist"><ms:Criterion xpath="true()"/></ms:Handling>
          <ms:Handling for="cascade-merge"><ms:Criterion xpath="true()"/></ms:Handling>
          <ms:Handling for="cascade-remove"><ms:Criterion xpath="true()"/></ms:Handling>
          <ms:Handling for="cascade-refresh"><ms:Criterion xpath="true()"/></ms:Handling>
       </ms:Handling>
       <ms:Handling for="order-by"><ms:Criterion xpath="true()"/></ms:Handling>
       <ms:Handling for="map-key"><ms:Criterion xpath="true()"/></ms:Handling>
  </ms:Handling>
  <ms:Handling for="basic">
        <ms:Handling for="column" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
        <ms:Handling for="lob" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
        <ms:Handling for="temporal" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
        <ms:Handling for="enumerated" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  </ms:Handling>
  <ms:Handling for="pre-persist" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="post-persist" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="pre-remove" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="post-remove" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="pre-update" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="post-update" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="post-load" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
</ms:MergeSchema>

=== jan-vcapgemini/lexeme/src/main/resources/mergeSchemas/springAOP.xml
<?xml version="1.0" encoding="UTF-8"?>
<ms:MergeSchema for="" root = "false" xmlns:ms="http://may-bee.github.io/lexeme/mergeschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://may-bee.github.io/lexeme/mergeschema ../xsd/MergeSchema.xsd ">
  <ms:Definition namespace="http://www.springframework.org/schema/aop"/>

  <ms:DefaultCriterion xpath="true()"/>

  <ms:Handling for="aspectj-autoproxy">
    <ms:Handling for="include">
      <ms:Criterion xpath="./@name"/>
    </ms:Handling>
  </ms:Handling>

  <ms:Handling for="config">
    <ms:Handling for="pointcut">
      <ms:Criterion xpath="./@id"/>
    </ms:Handling>
    <ms:Handling for="advisor">
      <ms:Criterion xpath="./@id"/>
    </ms:Handling>
    <ms:Handling for="aspect">
      <ms:Criterion xpath="./@id"/>
      <ms:Handling for="declare-parents">
        <ms:Criterion xpath="./@implement-interface"/>
      </ms:Handling>
      <ms:Handling for="before">
        <ms:Criterion xpath="./@method"/>
      </ms:Handling>
      <ms:Handling for="after">
        <ms:Criterion xpath="./@method"/>
      </ms:Handling>
      <ms:Handling for="around">
        <ms:Criterion xpath="./@method"/>
      </ms:Handling>
      <ms:Handling for="after-returning">
        <ms:Criterion xpath="./@method"/>
      </ms:Handling>
      <ms:Handling for="after-throwing">
        <ms:Criterion xpath="./@method"/>
      </ms:Handling>
    </ms:Handling>
  </ms:Handling>

</ms:MergeSchema>

=== jan-vcapgemini/lexeme/src/main/resources/mergeSchemas/springBeans.xml
<?xml version="1.0" encoding="UTF-8"?>
<ms:MergeSchema for="beans" xmlns:ms="http://may-bee.github.io/lexeme/mergeschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://may-bee.github.io/lexeme/mergeschema ../xsd/MergeSchema.xsd ">
	<!-- MergeSchema for spring bean documents. Patch document will be favored over base document -->
  <ms:Definition namespace="http://www.springframework.org/schema/beans"/>

  <ms:DefaultCriterion xpath="true()"/>

  <ms:Handling for="description" type="unique">
  	<ms:Criterion xpath="true()"/>
  </ms:Handling>
  <ms:Handling for="import">
    <ms:Criterion xpath="true()"/>
  </ms:Handling>
  <ms:Handling for="alias">
    <ms:Criterion xpath="true()"/>
  </ms:Handling>

  <ms:Handling for="bean" label="refListOrSetType">
    <ms:Criterion xpath="./@name"/>
  	<!-- Handling for description from the axis above -->
  	<ms:Handling for="constructor-arg">
      <ms:Criterion xpath="./@name"/>
  	</ms:Handling>

    <ms:Handling for="propertyType">
      <ms:Criterion xpath="./@name"/>
    </ms:Handling>

    <ms:Handling for="qualifier">
      <ms:Criterion xpath="./@type"/>
    </ms:Handling>

    <ms:Handling for="lookup-method">
      <ms:Criterion xpath="./@name"/>
    </ms:Handling>

    <ms:Handling for="replaced-method">
      <ms:Criterion xpath="./@name"/>
      <ms:Handling for="arg-type">
        <ms:Criterion xpath="./@match"/>
      </ms:Handling>
    </ms:Handling>

    <!-- shared Handlings -->
    <ms:Handling for="ref" type="unique">
      <ms:Criterion xpath="true()"/>
    </ms:Handling>
    <ms:Handling for="idref"  type="unique">
      <ms:Criterion xpath="true()"/>
    </ms:Handling>
    <ms:Handling for="value" type="unique">
      <ms:Criterion xpath="true()"/>
    </ms:Handling>
    <ms:Handling for="null"  type="unique">
      <ms:Criterion xpath="true()"/>
    </ms:Handling>
    <ms:Handling for="array" type="unique">
      <ms:Criterion xpath="true()"/>
    </ms:Handling>
    <ms:Handling for="list" type="unique">
      <ms:Criterion xpath="true()"/>
    </ms:Handling>
    <ms:Handling for="set" type="unique">
    <ms:Criterion xpath="true()"/>
    </ms:Handling>
    <ms:Handling for="map" type="unique">
    <ms:Criterion xpath="true()"/>
    </ms:Handling>
    <ms:Handling for="props" type="unique">
    <ms:Criterion xpath="true()"/>
    </ms:Handling>

  </ms:Handling> <!-- End Handling for bean -->

  <ms:Handling for="meta">
  	<ms:Criterion xpath="./@key"/>
  </ms:Handling>

</ms:MergeSchema>

=== jan-vcapgemini/lexeme/src/main/resources/mergeSchemas/beanMappings.xml
<?xml version="1.0" encoding="UTF-8"?>
<ms:MergeSchema for="mappings" xmlns:ms="http://may-bee.github.io/lexeme/mergeschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://may-bee.github.io/lexeme/mergeschema ../xsd/MergeSchema.xsd ">
  <ms:Definition namespace="http://dozer.sourceforge.net"/>

  <ms:Handling for="configuration" unique="true">
    <ms:Criterion xpath="true()"/>
    <ms:Handling for="stop-on-errors" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="date-format" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="wildcard" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="trim-strings" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="map-null" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="map-empty-string" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="bean-factory" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="relationship-type" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="custom-converters" unique="true">
      <ms:Criterion xpath="true()"/>
      <ms:Handling for="converter"><ms:Criterion xpath="./class-a"/></ms:Handling>
    </ms:Handling>
    <ms:Handling for="copy-by-references" unique="true">
      <ms:Criterion xpath="true()"/>
      <ms:Handling for="copy-by-reference"><ms:Criterion xpath="./text()"/></ms:Handling>
    </ms:Handling>
    <ms:Handling for="allowed-exceptions" unique="true">
      <ms:Criterion xpath="true()"/>
      <ms:Handling for="exception"><ms:Criterion xpath="./text()"/></ms:Handling>
    </ms:Handling>
    <ms:Handling for="variables" unique="true">
      <ms:Criterion xpath="true()"/>
      <ms:Handling for="variable"><ms:Criterion xpath="./@name"/></ms:Handling>
    </ms:Handling>
  </ms:Handling>
  <ms:Handling for="mapping">
    <ms:Criterion xpath="./@map-id"/>
    <ms:Handling for="field">
      <ms:Criterion xpath="./@map-id"/>
      <ms:Handling for="a-hint" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
      <ms:Handling for="b-hint" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
      <ms:Handling for="a-deep-index-hint" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
      <ms:Handling for="b-deep-index-hint" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    </ms:Handling>

    <ms:Handling for="field-exclude"><ms:Criterion xpath="./*" ordered="false"/></ms:Handling>

    <ms:Handling for="a" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
    <ms:Handling for="b" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>

  </ms:Handling>


  <ms:Handling for="class-a" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>
  <ms:Handling for="class-b" unique="true"><ms:Criterion xpath="true()"/></ms:Handling>

</ms:MergeSchema>

=== jan-vcapgemini/lexeme/src/test/resources/systemtests/mergeschemas/SecondMergeSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<ms:MergeSchema for="" xmlns:ms="http://may-bee.github.io/lexeme/mergeschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://may-bee.github.io/lexeme/mergeschema ../../../../main/resources/xsd/MergeSchema.xsd ">
  <ms:Definition location="src/test/resources/systemtests/schemas/SecondSchema.xsd" type="xsd" namespace = "http://www.example.org/SecondSchema"/>

  <ms:Handling for="B" unique="true">
    <ms:Criterion xpath="true()"/>
    <ms:Attribute for="id" attachable="true" separationString=";" />
  </ms:Handling>
  <ms:Handling for="C">
    <ms:Criterion xpath="./Ca/text()"/>
    <ms:Handling for="Ca" unique="true">
      <ms:Criterion xpath="true()"/>
    </ms:Handling>
    <ms:Handling for="Cb" >
      <ms:Criterion xpath="./text()"/>
    </ms:Handling>
  </ms:Handling>
</ms:MergeSchema>

=== jan-vcapgemini/lexeme/src/main/resources/mergeSchemas/springSecurity.xml
<?xml version="1.0" encoding="UTF-8"?>
<ms:MergeSchema for="" root="false" xmlns:ms="http://may-bee.github.io/lexeme/mergeschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://may-bee.github.io/lexeme/mergeschema ../xsd/MergeSchema.xsd ">
  <ms:Definition namespace="http://www.springframework.org/schema/security"/>

  <ms:DefaultCriterion xpath="true()"/>

  <ms:Handling for="attribute-exchange">
    <ms:Handling for="openid-attribute">
      <ms:Criterion xpath="./@name"/>
    </ms:Handling>
  </ms:Handling>

  <ms:Handling for="authentication-manager">
    <ms:Handling for="authentication-provider">
      <ms:Criterion xpath="./@ref"/>
      <ms:Handling for="password-encoder">
        <ms:Criterion xpath="./@ref"/>
      </ms:Handling>
    </ms:Handling>
    <ms:Handling for="ldap-authentication-provider">
      <ms:Criterion xpath="./@server-ref"/>
      <ms:Handling for="password-compare" unique="true">
        <ms:Handling for="password-encoder" unqiue="true"/>
      </ms:Handling>
    </ms:Handling>
    <!-- shared elements -->
    <ms:Handling for="salt-source" unique="true"/>
  </ms:Handling>

  <ms:Handling for="filter-chain">
    <ms:Attribute for="filters" attachable="true" separationString=","/>
  </ms:Handling>

  <ms:Handling for="filter-chain-map">
    <ms:Handling for="filter-chain">
      <ms:Criterion xpath="./@pattern"/>
    </ms:Handling>
  </ms:Handling>

  <ms:Handling for="global-method-security">
    <ms:Handling for="pre-post-annotation-handling" unique="true">
      <ms:Handling for="invocation-attribute-factory" unique="true"/>
      <ms:Handling for="pre-invocation-advice" unique="true"/>
      <ms:Handling for="post-invocation-advice" unique="true"/>
    </ms:Handling>
    <ms:Handling for="expression-handler" unique="true"/>
    <ms:Handling for="protect-pointcut">
      <ms:Criterion xpath="./@expression"/>
    </ms:Handling>
    <ms:Handling for="after-invocation-provider">
      <ms:Criterion xpath="./@ref"/>
    </ms:Handling>
  </ms:Handling>

  <ms:Handling for="http">
    <ms:Handling for="access-denied-handler">
      <ms:Criterion xpath="ref"/>
    </ms:Handling>
    <ms:Handling for="form-login">
      <ms:Criterion xpath="./@login-processing-url"/>
    </ms:Handling>
    <ms:Handling for="openid-login">
      <ms:Criterion xpath="./@login-process-url"/>
      <ms:Handling for="attribute-exchange">
        <ms:Criterion xpath="./child::openid-attribute/@name" ordered="false"/>
        <ms:Handling for="openid-attribute">
          <ms:Criterion xpath="./@name"/>
        </ms:Handling>
      </ms:Handling>
    </ms:Handling>
    <ms:Handling for="jee">
      <ms:Criterion xpath="./@user-service-ref"/>
      <ms:Attribute for="mappable-roles"  attachable="true" separationString="," />
    </ms:Handling>
    <ms:Handling for="http-basic">
      <ms:Criterion xpath="./@entry-point-ref"/>
    </ms:Handling>
    <ms:Handling for="logout">
      <ms:Criterion xpath="./@logout-url"/>
    </ms:Handling>
    <ms:Handling for="session-management">
      <ms:Handling for="concurrency-control" unique="true"/>
    </ms:Handling>
    <ms:Handling for="port-mappings">
      <ms:Handling for="port-mapping">
        <ms:Criterion xpath="./@http-port"/>
      </ms:Handling>
    </ms:Handling>
  </ms:Handling>

  <ms:Handling for="user-service">
    <ms:Handling for="user">
      <ms:Criterion xpath="./@name"/>
    </ms:Handling>
  </ms:Handling>

  <ms:Handling for="websocket-message-broker">
    <ms:Handling for="intercept-message">
      <ms:Criterion xpath="./@pattern"/>
    </ms:Handling>
  </ms:Handling>

  <!-- handled by default -->
    <!-- any-user-service -->
    <!-- cache-control -->
    <!-- content-type-options -->
    <!-- csrf -->
    <!-- custom-filter -->
    <!-- debug -->
    <!-- filter-security-metadata-source -->
    <!-- frame-options -->
    <!-- header -->
    <!-- headers -->
    <!-- http-firewall -->
    <!-- intercept-message -->
    <!-- jdbc-user-service -->
    <!-- jee -->
    <!-- ldap-server -->
    <!-- ldap-user-service -->
    <!-- method-security-metadata-source -->
    <!-- openid-attribute -->
    <!-- request-cache -->
    <!-- xss-protection -->

  <!-- shared elements -->
  <ms:Handling for="intercept-url">
    <ms:Criterion xpath="./@pattern"/>
  </ms:Handling>

  <ms:Handling for="protect">
    <ms:Criterion xpath="./@method"/>
  </ms:Handling>
</ms:MergeSchema>
